CREATE TABLE IF NOT EXISTS meow (
  id int(11) NOT NULL AUTO_INCREMENT,
  content text NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;